name: My Brain
favicon: null
layout_spectrum: 0.74182
typography_spectrum: 0.31683
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f9d85'
    - '#88b2c0'
    - '#3b7777'
    - '#1c1a2f'
    - '#b0d5c7'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
