name: My Brain
favicon: null
layout_spectrum: 0.6189005840569735
typography_spectrum: 0.9540368251036853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.24585514678619802
  lightness: 0.9309306214563549
  saturation: 0.6176505512557924
  rhythmicContrast: 0.4002079013735056
purpose: []
