name: My Brain
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1489a5'
    - '#e5b093'
    - '#003e54'
    - '#8ec8dc'
    - '#a5511e'
  brandStrength: 0.5
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.4002079013735056
purpose: []
